// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAO7DMmf5hwTMhRiSHjDQ2Fr0h3h6iaDyw',
    appId: '1:740431591418:web:72dc6b71f5ad28961f1643',
    messagingSenderId: '740431591418',
    projectId: 'bdflutter-d621c',
    authDomain: 'bdflutter-d621c.firebaseapp.com',
    storageBucket: 'bdflutter-d621c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD354ZC6tQh_Qg1HAFJEfmCSBXclGJs0lo',
    appId: '1:740431591418:android:31e5bdd511411afa1f1643',
    messagingSenderId: '740431591418',
    projectId: 'bdflutter-d621c',
    storageBucket: 'bdflutter-d621c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBh87714aWmosfvWQnKt_2_yBe6GKt0T48',
    appId: '1:740431591418:ios:9224e96600a6aaeb1f1643',
    messagingSenderId: '740431591418',
    projectId: 'bdflutter-d621c',
    storageBucket: 'bdflutter-d621c.firebasestorage.app',
    iosBundleId: 'com.example.bdFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBh87714aWmosfvWQnKt_2_yBe6GKt0T48',
    appId: '1:740431591418:ios:9224e96600a6aaeb1f1643',
    messagingSenderId: '740431591418',
    projectId: 'bdflutter-d621c',
    storageBucket: 'bdflutter-d621c.firebasestorage.app',
    iosBundleId: 'com.example.bdFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAO7DMmf5hwTMhRiSHjDQ2Fr0h3h6iaDyw',
    appId: '1:740431591418:web:715e37ea0f57edcb1f1643',
    messagingSenderId: '740431591418',
    projectId: 'bdflutter-d621c',
    authDomain: 'bdflutter-d621c.firebaseapp.com',
    storageBucket: 'bdflutter-d621c.firebasestorage.app',
  );

}